# Generated by Django 5.1.3 on 2025-04-07 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CoordenadoriaHospitalMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadoria_hospital', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisaoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisao_tecnica', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LocalTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_trabalho', models.CharField(max_length=255)),
                ('local_coordenadoria_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.coordenadoriahospitalmunicipal')),
                ('local_supervisao_tecnica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.supervisaotecnica')),
            ],
        ),
        migrations.CreateModel(
            name='InformacoePessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=80, verbose_name='Sobrenome')),
                ('cidade', models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade')),
                ('pais', models.CharField(blank=True, max_length=70, null=True, verbose_name='Pais')),
                ('fone', models.CharField(max_length=14)),
                ('sexo', models.CharField(choices=[('Feminino', 'feminino'), ('Masculino', 'masculino'), ('Intersexo', 'Intersexo'), ('Não-binárion', 'nao-binario'), ('Prefiro não declararar', 'nao-declarado')], default=None, max_length=22, verbose_name='Gênero')),
                ('cor', models.CharField(choices=[('Branca', 'branca'), ('Parda', 'parda'), ('Preta', 'preta'), ('Amarela', 'amarela'), ('Indigena', 'indigena')], default=None, max_length=10, verbose_name='Raça/Cor')),
                ('rg', models.CharField(max_length=9)),
                ('nome_social', models.CharField(max_length=100, verbose_name='Nome Social')),
                ('escolaridade', models.CharField(choices=[('Ensino Fundamental', 'fundamental'), ('Ensino Médio', 'medio'), ('Superior', 'superior'), ('Mestrado', 'mestrado'), ('Doutorado', 'doutorado')], default=None, max_length=18)),
                ('vinculo', models.CharField(choices=[('Direta PMSP', 'direta-pmsp'), ('Organizações Sociais', 'organizacao-social'), ('Admitido', 'admitido'), ('CLT', 'clt'), ('Lei 500', 'lei-500'), ('Prestador Externo', 'prestador-externo'), ('PJ', 'pj')], default=None, max_length=20, verbose_name='Vínculo Empregatício')),
                ('registro_funciona', models.CharField(blank=True, max_length=11, null=True, verbose_name='RF Registro Funcional')),
                ('grupo_relatorio', models.CharField(choices=[('ATI T2023 R2', 'ati-t2023-r2'), ('BMF T2023 R2', 'bmf-t2023-r2'), ('NEO T2023 R2', 'neo-t2023-r2'), ('UE T2023 R2', 'ue-t2023-r2'), ('PICS T2023 R2', 'pics-t2023-r2'), ('ATI T2024 R1', 'ati-t2024-r1'), ('BMF T2024 R1', 'bmf-t2024-r1'), ('NEO T2024 R1', 'neo-t2024-r1'), ('UE T2024 R1', 'ue-t2024-r1'), ('PICS T2024 R1', 'pics-t2024-r1'), ('BMF T2022 R3', 'bmf-t2022-r3')], default=None, max_length=15, verbose_name='Grupo Relatorio')),
                ('ramal', models.CharField(max_length=14)),
                ('categoria_profissiona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.categoriaprofissional')),
                ('local_trabalho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.localtrabalho')),
            ],
        ),
    ]
