# Generated by Django 5.1.3 on 2025-04-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoepessoal',
            name='nome_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Social'),
        ),
    ]
