# Generated by Django 5.1.3 on 2025-05-07 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_informacoepessoal_nome_social'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacoepessoal',
            name='categoria_profissiona',
        ),
        migrations.RemoveField(
            model_name='localtrabalho',
            name='local_coordenadoria_hospital',
        ),
        migrations.RemoveField(
            model_name='informacoepessoal',
            name='local_trabalho',
        ),
        migrations.RemoveField(
            model_name='localtrabalho',
            name='local_supervisao_tecnica',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CategoriaProfissional',
        ),
        migrations.DeleteModel(
            name='CoordenadoriaHospitalMunicipal',
        ),
        migrations.DeleteModel(
            name='InformacoePessoal',
        ),
        migrations.DeleteModel(
            name='LocalTrabalho',
        ),
        migrations.DeleteModel(
            name='SupervisaoTecnica',
        ),
    ]
